// Generated by dojo-bindgen on Wed, 12 Jun 2024 06:17:57 +0000. Do not modify this file manually.
using System;
using Dojo;
using Dojo.Starknet;

namespace Game
{
    // Model definition for `dojo_starter::models::counter::Counter` model
    public class Counter : ModelInstance {
        [ModelField("entityId")]
        public uint entityId;

        [ModelField("counter")]
        public uint counter;

        // Start is called before the first frame update
        void Start() {
        }

        // Update is called once per frame
        void Update() {
        }
    }
}
        