// Generated by dojo-bindgen on Wed, 12 Jun 2024 06:17:57 +0000. Do not modify this file manually.
using System;
using Dojo;
using Dojo.Starknet;

namespace Game
{
    // Model definition for `dojo_starter::models::health::Health` model
    public class Health : ModelInstance {
        [ModelField("entityId")]
        public FieldElement entityId;

        [ModelField("gameId")]
        public uint gameId;

        [ModelField("health")]
        public ushort health;

        // Start is called before the first frame update
        void Start() {
        }

        // Update is called once per frame
        void Update() {
        }
    }
            

}